version: '3.6'

services:
  db:
    image: postgres:16.2
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - services-network

  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    networks:
      - services-network
    depends_on:
      - db
    volumes:
      - .:/app



networks:
  services-network:
    driver: bridge